"""standardize_check_constraints_and_indexes

Revision ID: bc272bf8d404
Revises: f2a3b4c5d6e7
Create Date: 2026-08-25 14:46:18.630349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc272bf8d404"
down_revision: Union[str, Sequence[str], None] = "f2a3b4c5d6e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bot_scheduler_runs",
        "status",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "running",
            "completed",
            "failed",
            name="check_bot_scheduler_runs_status",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'running'::text"),
    )
    op.drop_constraint(
        op.f("bot_scheduler_runs_status_check"), "bot_scheduler_runs", type_="check"
    )
    op.alter_column(
        "bot_telegram_audio_cache",
        "send_method",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "voice",
            "audio",
            "document",
            name="check_bot_audio_cache_method",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("bot_audio_cache_method_check"), "bot_telegram_audio_cache", type_="check"
    )
    op.alter_column(
        "bot_user_cards",
        "status",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "reserved",
            "delivered",
            "failed",
            name="check_bot_user_cards_status",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'reserved'::text"),
    )
    op.drop_index(op.f("bot_user_cards_delivered_at_idx"), table_name="bot_user_cards")
    op.drop_index(op.f("bot_user_cards_entry_idx"), table_name="bot_user_cards")
    op.drop_index(op.f("bot_user_cards_error_idx"), table_name="bot_user_cards")
    op.drop_index(
        op.f("bot_user_cards_user_entry_active_uidx"),
        table_name="bot_user_cards",
        postgresql_where="(status = ANY (ARRAY['delivered'::text, 'reserved'::text]))",
    )
    op.drop_index(
        op.f("bot_user_cards_user_slot_active_uidx"),
        table_name="bot_user_cards",
        postgresql_where="(status = ANY (ARRAY['delivered'::text, 'reserved'::text]))",
    )
    op.drop_index(op.f("bot_user_cards_user_status_idx"), table_name="bot_user_cards")
    op.create_index(
        op.f("ix_bot_user_cards_delivered_at"),
        "bot_user_cards",
        ["delivered_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bot_user_cards_entry_id"), "bot_user_cards", ["entry_id"], unique=False
    )
    op.create_index(
        "ix_bot_user_cards_error",
        "bot_user_cards",
        ["status", "error_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_bot_user_cards_user_status",
        "bot_user_cards",
        ["telegram_user_id", "status"],
        unique=False,
    )
    op.create_index(
        "uix_bot_user_cards_user_entry_active",
        "bot_user_cards",
        ["telegram_user_id", "entry_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('delivered', 'reserved')"),
    )
    op.create_index(
        "uix_bot_user_cards_user_slot_active",
        "bot_user_cards",
        ["telegram_user_id", "scheduled_slot"],
        unique=True,
        postgresql_where=sa.text("status IN ('delivered', 'reserved')"),
    )
    op.drop_constraint(
        op.f("bot_user_cards_dialect_check"), "bot_user_cards", type_="check"
    )
    op.drop_constraint(
        op.f("bot_user_cards_status_check"), "bot_user_cards", type_="check"
    )
    op.alter_column(
        "bot_users",
        "role",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "user",
            "admin",
            name="check_bot_users_role",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::text"),
    )
    op.drop_index(op.f("bot_users_active_idx"), table_name="bot_users")
    op.drop_index(op.f("bot_users_role_idx"), table_name="bot_users")
    op.create_index(
        "ix_bot_users_active",
        "bot_users",
        ["is_active", "onboarding_completed"],
        unique=False,
    )
    op.create_index(op.f("ix_bot_users_role"), "bot_users", ["role"], unique=False)
    op.drop_constraint(op.f("bot_users_dialect_check"), "bot_users", type_="check")
    op.drop_constraint(op.f("bot_users_levels_check"), "bot_users", type_="check")
    op.drop_constraint(op.f("bot_users_role_check"), "bot_users", type_="check")
    op.alter_column(
        "oald_audio_files",
        "download_status",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "pending",
            "downloaded",
            "failed",
            name="check_oald_audio_status",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.drop_index(
        op.f("oald_audio_sha256_idx"),
        table_name="oald_audio_files",
        postgresql_where="(sha256 <> ''::bpchar)",
    )
    op.create_index(
        "ix_oald_audio_sha256",
        "oald_audio_files",
        ["sha256"],
        unique=False,
        postgresql_where=sa.text("sha256 != ''"),
    )
    op.drop_constraint(
        op.f("oald_audio_attempt_count_check"), "oald_audio_files", type_="check"
    )
    op.drop_constraint(op.f("oald_audio_size_check"), "oald_audio_files", type_="check")
    op.drop_constraint(
        op.f("oald_audio_status_check"), "oald_audio_files", type_="check"
    )
    op.alter_column(
        "oald_audio_variants",
        "variant_type",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "telegram_voice_opus",
            name="check_oald_audio_variants_type",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "oald_audio_variants",
        "conversion_status",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "pending",
            "prepared",
            "failed",
            name="check_oald_audio_variants_status",
            native_enum=False,
            create_constraint=True,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.drop_index(
        op.f("oald_audio_variants_status_idx"), table_name="oald_audio_variants"
    )
    op.create_index(
        "ix_oald_audio_variants_status",
        "oald_audio_variants",
        ["variant_type", "conversion_status"],
        unique=False,
    )
    op.drop_constraint(
        op.f("oald_audio_variant_attempt_count_check"),
        "oald_audio_variants",
        type_="check",
    )
    op.drop_constraint(
        op.f("oald_audio_variant_size_check"), "oald_audio_variants", type_="check"
    )
    op.drop_constraint(
        op.f("oald_audio_variant_status_check"), "oald_audio_variants", type_="check"
    )
    op.drop_constraint(
        op.f("oald_audio_variant_type_check"), "oald_audio_variants", type_="check"
    )
    op.drop_index(op.f("oald_entries_active_idx"), table_name="oald_entries")
    op.drop_index(op.f("oald_entries_category_idx"), table_name="oald_entries")
    op.drop_index(op.f("oald_entries_cefr_idx"), table_name="oald_entries")
    op.drop_index(
        op.f("oald_entries_translations_idx"),
        table_name="oald_entries",
        postgresql_using="gin",
    )
    op.drop_index(op.f("oald_entries_word_gb_idx"), table_name="oald_entries")
    op.drop_index(op.f("oald_entries_word_us_category_idx"), table_name="oald_entries")
    op.drop_index(op.f("oald_entries_word_us_idx"), table_name="oald_entries")
    op.create_index(
        "ix_oald_entries_active", "oald_entries", ["is_active", "cefr"], unique=False
    )
    op.create_index(
        op.f("ix_oald_entries_cefr"), "oald_entries", ["cefr"], unique=False
    )
    op.create_index(
        op.f("ix_oald_entries_lexical_category"),
        "oald_entries",
        ["lexical_category"],
        unique=False,
    )
    op.create_index(
        "ix_oald_entries_translations",
        "oald_entries",
        ["translations"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_oald_entries_word_gb"), "oald_entries", ["word_gb"], unique=False
    )
    op.create_index(
        op.f("ix_oald_entries_word_us"), "oald_entries", ["word_us"], unique=False
    )
    op.create_index(
        "ix_oald_entries_word_us_category",
        "oald_entries",
        ["word_us", "lexical_category"],
        unique=False,
    )
    op.drop_constraint(
        op.f("oald_entries_category_check"), "oald_entries", type_="check"
    )
    op.drop_constraint(op.f("oald_entries_cefr_check"), "oald_entries", type_="check")
    op.drop_constraint(
        op.f("oald_entries_definition_url_check"), "oald_entries", type_="check"
    )
    op.drop_constraint(
        op.f("oald_entries_word_gb_check"), "oald_entries", type_="check"
    )
    op.drop_constraint(
        op.f("oald_entries_word_us_check"), "oald_entries", type_="check"
    )
    op.drop_index(
        op.f("oald_entry_audio_dialect_idx"), table_name="oald_entry_audio_sources"
    )
    op.drop_index(
        op.f("oald_entry_audio_source_url_idx"), table_name="oald_entry_audio_sources"
    )
    op.create_index(
        op.f("ix_oald_entry_audio_sources_dialect"),
        "oald_entry_audio_sources",
        ["dialect"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oald_entry_audio_sources_source_url"),
        "oald_entry_audio_sources",
        ["source_url"],
        unique=False,
    )
    op.drop_constraint(
        op.f("oald_entry_audio_dialect_check"),
        "oald_entry_audio_sources",
        type_="check",
    )
    op.drop_constraint(
        op.f("oald_entry_audio_position_check"),
        "oald_entry_audio_sources",
        type_="check",
    )
    op.drop_index(
        op.f("oxford_lexical_entries_category_idx"), table_name="oxford_lexical_entries"
    )
    op.drop_index(
        op.f("oxford_lexical_entries_translations_idx"),
        table_name="oxford_lexical_entries",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("oxford_lexical_entries_word_gb_idx"), table_name="oxford_lexical_entries"
    )
    op.drop_index(
        op.f("oxford_lexical_entries_word_us_idx"), table_name="oxford_lexical_entries"
    )
    op.create_index(
        op.f("ix_oxford_lexical_entries_lexical_category"),
        "oxford_lexical_entries",
        ["lexical_category"],
        unique=False,
    )
    op.create_index(
        "ix_oxford_lexical_entries_translations",
        "oxford_lexical_entries",
        ["translations"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_oxford_lexical_entries_word_gb"),
        "oxford_lexical_entries",
        ["word_gb"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oxford_lexical_entries_word_us"),
        "oxford_lexical_entries",
        ["word_us"],
        unique=False,
    )
    op.drop_constraint(
        op.f("oxford_lexical_entries_gb_pronunciation_check"),
        "oxford_lexical_entries",
        type_="check",
    )
    op.drop_constraint(
        op.f("oxford_lexical_entries_us_pronunciation_check"),
        "oxford_lexical_entries",
        type_="check",
    )
    op.create_check_constraint(
        "check_oxford_lexical_entries_gb_pronunciation",
        "oxford_lexical_entries",
        "cardinality(ipa_gb) = cardinality(audio_source_gb)",
    )
    op.create_check_constraint(
        "check_oxford_lexical_entries_us_pronunciation",
        "oxford_lexical_entries",
        "cardinality(ipa_us) = cardinality(audio_source_us)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_oxford_lexical_entries_us_pronunciation",
        "oxford_lexical_entries",
        type_="check",
    )
    op.drop_constraint(
        "check_oxford_lexical_entries_gb_pronunciation",
        "oxford_lexical_entries",
        type_="check",
    )
    op.create_check_constraint(
        op.f("oxford_lexical_entries_us_pronunciation_check"),
        "oxford_lexical_entries",
        "cardinality(ipa_us) = cardinality(audio_source_us)",
    )
    op.create_check_constraint(
        op.f("oxford_lexical_entries_gb_pronunciation_check"),
        "oxford_lexical_entries",
        "cardinality(ipa_gb) = cardinality(audio_source_gb)",
    )
    op.drop_index(
        op.f("ix_oxford_lexical_entries_word_us"), table_name="oxford_lexical_entries"
    )
    op.drop_index(
        op.f("ix_oxford_lexical_entries_word_gb"), table_name="oxford_lexical_entries"
    )
    op.drop_index(
        "ix_oxford_lexical_entries_translations",
        table_name="oxford_lexical_entries",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_oxford_lexical_entries_lexical_category"),
        table_name="oxford_lexical_entries",
    )
    op.create_index(
        op.f("oxford_lexical_entries_word_us_idx"),
        "oxford_lexical_entries",
        ["word_us"],
        unique=False,
    )
    op.create_index(
        op.f("oxford_lexical_entries_word_gb_idx"),
        "oxford_lexical_entries",
        ["word_gb"],
        unique=False,
    )
    op.create_index(
        op.f("oxford_lexical_entries_translations_idx"),
        "oxford_lexical_entries",
        ["translations"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("oxford_lexical_entries_category_idx"),
        "oxford_lexical_entries",
        ["lexical_category"],
        unique=False,
    )
    op.create_check_constraint(
        op.f("oald_entry_audio_position_check"),
        "oald_entry_audio_sources",
        "source_position >= 0",
    )
    op.create_check_constraint(
        op.f("oald_entry_audio_dialect_check"),
        "oald_entry_audio_sources",
        "dialect::text = ANY (ARRAY['us'::character varying::text, 'gb'::character varying::text])",
    )
    op.drop_index(
        op.f("ix_oald_entry_audio_sources_source_url"),
        table_name="oald_entry_audio_sources",
    )
    op.drop_index(
        op.f("ix_oald_entry_audio_sources_dialect"),
        table_name="oald_entry_audio_sources",
    )
    op.create_index(
        op.f("oald_entry_audio_source_url_idx"),
        "oald_entry_audio_sources",
        ["source_url"],
        unique=False,
    )
    op.create_index(
        op.f("oald_entry_audio_dialect_idx"),
        "oald_entry_audio_sources",
        ["dialect"],
        unique=False,
    )
    op.create_check_constraint(
        op.f("oald_entries_word_us_check"), "oald_entries", "btrim(word_us) <> ''::text"
    )
    op.create_check_constraint(
        op.f("oald_entries_word_gb_check"), "oald_entries", "btrim(word_gb) <> ''::text"
    )
    op.create_check_constraint(
        op.f("oald_entries_definition_url_check"),
        "oald_entries",
        "btrim(definition_url_oxford) <> ''::text",
    )
    op.create_check_constraint(
        op.f("oald_entries_cefr_check"),
        "oald_entries",
        "cefr::text = ANY (ARRAY['a1'::character varying, 'a2'::character varying, 'b1'::character varying, 'b2'::character varying, 'c1'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("oald_entries_category_check"),
        "oald_entries",
        "btrim(lexical_category) <> ''::text",
    )
    op.drop_index("ix_oald_entries_word_us_category", table_name="oald_entries")
    op.drop_index(op.f("ix_oald_entries_word_us"), table_name="oald_entries")
    op.drop_index(op.f("ix_oald_entries_word_gb"), table_name="oald_entries")
    op.drop_index(
        "ix_oald_entries_translations",
        table_name="oald_entries",
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_oald_entries_lexical_category"), table_name="oald_entries")
    op.drop_index(op.f("ix_oald_entries_cefr"), table_name="oald_entries")
    op.drop_index("ix_oald_entries_active", table_name="oald_entries")
    op.create_index(
        op.f("oald_entries_word_us_idx"), "oald_entries", ["word_us"], unique=False
    )
    op.create_index(
        op.f("oald_entries_word_us_category_idx"),
        "oald_entries",
        ["word_us", "lexical_category"],
        unique=False,
    )
    op.create_index(
        op.f("oald_entries_word_gb_idx"), "oald_entries", ["word_gb"], unique=False
    )
    op.create_index(
        op.f("oald_entries_translations_idx"),
        "oald_entries",
        ["translations"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("oald_entries_cefr_idx"), "oald_entries", ["cefr"], unique=False
    )
    op.create_index(
        op.f("oald_entries_category_idx"),
        "oald_entries",
        ["lexical_category"],
        unique=False,
    )
    op.create_index(
        op.f("oald_entries_active_idx"),
        "oald_entries",
        ["is_active", "cefr"],
        unique=False,
    )
    op.create_check_constraint(
        op.f("oald_audio_variant_type_check"),
        "oald_audio_variants",
        "variant_type = 'telegram_voice_opus'::text",
    )
    op.create_check_constraint(
        op.f("oald_audio_variant_status_check"),
        "oald_audio_variants",
        "conversion_status = ANY (ARRAY['pending'::text, 'prepared'::text, 'failed'::text])",
    )
    op.create_check_constraint(
        op.f("oald_audio_variant_size_check"),
        "oald_audio_variants",
        "size_bytes IS NULL OR size_bytes >= 0",
    )
    op.create_check_constraint(
        op.f("oald_audio_variant_attempt_count_check"),
        "oald_audio_variants",
        "attempt_count >= 0",
    )
    op.drop_index("ix_oald_audio_variants_status", table_name="oald_audio_variants")
    op.create_index(
        op.f("oald_audio_variants_status_idx"),
        "oald_audio_variants",
        ["variant_type", "conversion_status"],
        unique=False,
    )
    op.alter_column(
        "oald_audio_variants",
        "conversion_status",
        existing_type=sa.Enum(
            "pending",
            "prepared",
            "failed",
            name="check_oald_audio_variants_status",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.alter_column(
        "oald_audio_variants",
        "variant_type",
        existing_type=sa.Enum(
            "telegram_voice_opus",
            name="check_oald_audio_variants_type",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_check_constraint(
        op.f("oald_audio_status_check"),
        "oald_audio_files",
        "download_status = ANY (ARRAY['pending'::text, 'downloaded'::text, 'failed'::text])",
    )
    op.create_check_constraint(
        op.f("oald_audio_size_check"),
        "oald_audio_files",
        "size_bytes IS NULL OR size_bytes >= 0",
    )
    op.create_check_constraint(
        op.f("oald_audio_attempt_count_check"), "oald_audio_files", "attempt_count >= 0"
    )
    op.drop_index(
        "ix_oald_audio_sha256",
        table_name="oald_audio_files",
        postgresql_where=sa.text("sha256 != ''"),
    )
    op.create_index(
        op.f("oald_audio_sha256_idx"),
        "oald_audio_files",
        ["sha256"],
        unique=False,
        postgresql_where="(sha256 <> ''::bpchar)",
    )
    op.alter_column(
        "oald_audio_files",
        "download_status",
        existing_type=sa.Enum(
            "pending",
            "downloaded",
            "failed",
            name="check_oald_audio_status",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.create_check_constraint(
        op.f("bot_users_role_check"),
        "bot_users",
        "role = ANY (ARRAY['user'::text, 'admin'::text])",
    )
    op.create_check_constraint(
        op.f("bot_users_levels_check"),
        "bot_users",
        "selected_levels <@ ARRAY['a1'::text, 'a2'::text, 'b1'::text, 'b2'::text, 'c1'::text]",
    )
    op.create_check_constraint(
        op.f("bot_users_dialect_check"),
        "bot_users",
        "dialect IS NULL OR (dialect::text = ANY (ARRAY['us'::character varying, 'gb'::character varying, 'both'::character varying]::text[]))",
    )
    op.drop_index(op.f("ix_bot_users_role"), table_name="bot_users")
    op.drop_index("ix_bot_users_active", table_name="bot_users")
    op.create_index(op.f("bot_users_role_idx"), "bot_users", ["role"], unique=False)
    op.create_index(
        op.f("bot_users_active_idx"),
        "bot_users",
        ["is_active", "onboarding_completed"],
        unique=False,
    )
    op.alter_column(
        "bot_users",
        "role",
        existing_type=sa.Enum(
            "user",
            "admin",
            name="check_bot_users_role",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::text"),
    )
    op.create_check_constraint(
        op.f("bot_user_cards_status_check"),
        "bot_user_cards",
        "status = ANY (ARRAY['reserved'::text, 'delivered'::text, 'failed'::text])",
    )
    op.create_check_constraint(
        op.f("bot_user_cards_dialect_check"),
        "bot_user_cards",
        "dialect::text = ANY (ARRAY['us'::character varying::text, 'gb'::character varying::text, 'both'::character varying::text])",
    )
    op.drop_index(
        "uix_bot_user_cards_user_slot_active",
        table_name="bot_user_cards",
        postgresql_where=sa.text("status IN ('delivered', 'reserved')"),
    )
    op.drop_index(
        "uix_bot_user_cards_user_entry_active",
        table_name="bot_user_cards",
        postgresql_where=sa.text("status IN ('delivered', 'reserved')"),
    )
    op.drop_index("ix_bot_user_cards_user_status", table_name="bot_user_cards")
    op.drop_index("ix_bot_user_cards_error", table_name="bot_user_cards")
    op.drop_index(op.f("ix_bot_user_cards_entry_id"), table_name="bot_user_cards")
    op.drop_index(op.f("ix_bot_user_cards_delivered_at"), table_name="bot_user_cards")
    op.create_index(
        op.f("bot_user_cards_user_status_idx"),
        "bot_user_cards",
        ["telegram_user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("bot_user_cards_user_slot_active_uidx"),
        "bot_user_cards",
        ["telegram_user_id", "scheduled_slot"],
        unique=True,
        postgresql_where="(status = ANY (ARRAY['delivered'::text, 'reserved'::text]))",
    )
    op.create_index(
        op.f("bot_user_cards_user_entry_active_uidx"),
        "bot_user_cards",
        ["telegram_user_id", "entry_id"],
        unique=True,
        postgresql_where="(status = ANY (ARRAY['delivered'::text, 'reserved'::text]))",
    )
    op.create_index(
        op.f("bot_user_cards_error_idx"),
        "bot_user_cards",
        ["status", "error_type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("bot_user_cards_entry_idx"), "bot_user_cards", ["entry_id"], unique=False
    )
    op.create_index(
        op.f("bot_user_cards_delivered_at_idx"),
        "bot_user_cards",
        ["delivered_at"],
        unique=False,
    )
    op.alter_column(
        "bot_user_cards",
        "status",
        existing_type=sa.Enum(
            "reserved",
            "delivered",
            "failed",
            name="check_bot_user_cards_status",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'reserved'::text"),
    )
    op.create_check_constraint(
        op.f("bot_audio_cache_method_check"),
        "bot_telegram_audio_cache",
        "send_method = ANY (ARRAY['voice'::text, 'audio'::text, 'document'::text])",
    )
    op.alter_column(
        "bot_telegram_audio_cache",
        "send_method",
        existing_type=sa.Enum(
            "voice",
            "audio",
            "document",
            name="check_bot_audio_cache_method",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_check_constraint(
        op.f("bot_scheduler_runs_status_check"),
        "bot_scheduler_runs",
        "status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text])",
    )
    op.alter_column(
        "bot_scheduler_runs",
        "status",
        existing_type=sa.Enum(
            "running",
            "completed",
            "failed",
            name="check_bot_scheduler_runs_status",
            native_enum=False,
            create_constraint=True,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'running'::text"),
    )
    # ### end Alembic commands ###
