"""delete constrains

Revision ID: 00fc0919ab0a
Revises: bc272bf8d404
Create Date: 2026-08-26 14:36:37.180424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fc0919ab0a'
down_revision: Union[str, Sequence[str], None] = 'bc272bf8d404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('check_bot_scheduler_runs_status'), 'bot_scheduler_runs', type_='check')
    op.drop_constraint(op.f('check_bot_audio_cache_method'), 'bot_telegram_audio_cache', type_='check')
    op.drop_constraint(op.f('check_bot_user_cards_status'), 'bot_user_cards', type_='check')
    op.drop_constraint(op.f('check_bot_users_role'), 'bot_users', type_='check')
    op.drop_constraint(op.f('check_oald_audio_status'), 'oald_audio_files', type_='check')
    op.drop_constraint(op.f('check_oald_audio_variants_status'), 'oald_audio_variants', type_='check')
    op.drop_constraint(op.f('check_oald_audio_variants_type'), 'oald_audio_variants', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('check_oald_audio_variants_type'), 'oald_audio_variants', "variant_type::text = 'telegram_voice_opus'::text")
    op.create_check_constraint(op.f('check_oald_audio_variants_status'), 'oald_audio_variants', "conversion_status::text = ANY (ARRAY['pending'::character varying::text, 'prepared'::character varying::text, 'failed'::character varying::text])")
    op.create_check_constraint(op.f('check_oald_audio_status'), 'oald_audio_files', "download_status::text = ANY (ARRAY['pending'::character varying::text, 'downloaded'::character varying::text, 'failed'::character varying::text])")
    op.create_check_constraint(op.f('check_bot_users_role'), 'bot_users', "role::text = ANY (ARRAY['user'::character varying::text, 'admin'::character varying::text])")
    op.create_check_constraint(op.f('check_bot_user_cards_status'), 'bot_user_cards', "status::text = ANY (ARRAY['reserved'::character varying::text, 'delivered'::character varying::text, 'failed'::character varying::text])")
    op.create_check_constraint(op.f('check_bot_audio_cache_method'), 'bot_telegram_audio_cache', "send_method::text = ANY (ARRAY['voice'::character varying::text, 'audio'::character varying::text, 'document'::character varying::text])")
    op.create_check_constraint(op.f('check_bot_scheduler_runs_status'), 'bot_scheduler_runs', "status::text = ANY (ARRAY['running'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text])")
    # ### end Alembic commands ###
