"""delete is_active column from OaldEntry

Revision ID: ffe0c99e7a91
Revises: 00fc0919ab0a
Create Date: 2026-08-26 14:56:54.446414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe0c99e7a91'
down_revision: Union[str, Sequence[str], None] = '00fc0919ab0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oald_entries_active'), table_name='oald_entries')
    op.drop_column('oald_entries', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oald_entries', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_oald_entries_active'), 'oald_entries', ['is_active', 'cefr'], unique=False)
    # ### end Alembic commands ###
