"""baseline schema

Revision ID: 0bf7b06e17cf
Revises: 
Create Date: 2026-08-07 21:19:46.576639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bf7b06e17cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


MANAGED_TABLE_COLUMNS = {
    "oald_entries": {
        "id", "word_us", "word_gb", "lexical_category", "cefr",
        "definition_url_oxford", "definition_url_cambridge", "ipa_us",
        "ipa_gb", "definition", "example", "audio_source_us",
        "audio_source_gb", "translations", "is_active", "created_at",
        "updated_at",
    },
    "oald_audio_files": {
        "source_url", "audio_data", "content_type", "filename", "size_bytes",
        "sha256", "download_status", "last_http_status", "last_error",
        "attempt_count", "last_attempted_at", "downloaded_at", "created_at",
        "updated_at",
    },
    "oald_entry_audio_sources": {
        "entry_id", "dialect", "source_position", "source_url",
    },
    "oald_audio_variants": {
        "source_url", "variant_type", "source_sha256", "audio_data",
        "content_type", "filename", "size_bytes", "sha256",
        "conversion_status", "last_error", "attempt_count", "converted_at",
        "created_at", "updated_at",
    },
    "bot_users": {
        "telegram_user_id", "chat_id", "username", "first_name",
        "selected_levels", "pronunciation", "onboarding_completed",
        "is_active", "created_at", "updated_at", "last_delivery_at",
        "paused_at", "blocked_at",
    },
    "bot_user_cards": {
        "id", "telegram_user_id", "entry_id", "dialect", "source_url",
        "source_url_gb", "scheduled_slot", "status", "telegram_message_id",
        "error_type", "error_message", "created_at", "delivered_at",
    },
    "bot_scheduler_runs": {
        "scheduled_slot", "status", "attempted_users", "delivered_cards",
        "failed_cards", "skipped_users", "started_at", "completed_at",
        "error_message",
    },
    "bot_telegram_audio_cache": {
        "source_url", "send_method", "telegram_file_id", "updated_at",
    },
    # oxford_lexical_entries is added later (c7d8e9f0a1b2); do not require it
    # when adopting pre-Alembic seed databases.
}


def legacy_schema_is_complete() -> bool:
    inspector = sa.inspect(op.get_bind())
    existing = set(inspector.get_table_names()) & set(MANAGED_TABLE_COLUMNS)
    if not existing:
        return False
    expected = set(MANAGED_TABLE_COLUMNS)
    if existing != expected:
        missing = ", ".join(sorted(expected - existing))
        raise RuntimeError(
            "Partially initialized managed schema; missing tables: "
            f"{missing}. Restore a complete seed or rebuild the database."
        )
    for table_name, required in MANAGED_TABLE_COLUMNS.items():
        actual = {
            column["name"] for column in inspector.get_columns(table_name)
        }
        missing_columns = required - actual
        if missing_columns:
            missing = ", ".join(sorted(missing_columns))
            raise RuntimeError(
                f"Legacy table {table_name!r} is missing columns: {missing}"
            )
    return True


def upgrade() -> None:
    """Upgrade schema."""
    # Existing seed/prod databases predate Alembic but already have the full
    # schema. Validate their shape and adopt them without touching data.
    if legacy_schema_is_complete():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_scheduler_runs',
    sa.Column('scheduled_slot', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('attempted_users', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('delivered_cards', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_cards', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('skipped_users', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='bot_scheduler_runs_status_check'),
    sa.PrimaryKeyConstraint('scheduled_slot')
    )
    op.create_table('bot_users',
    sa.Column('telegram_user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('first_name', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('selected_levels', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('pronunciation', sa.String(length=4), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_delivery_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('paused_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('blocked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("pronunciation IS NULL OR pronunciation IN ('us', 'gb', 'both')", name='bot_users_pronunciation_check'),
    sa.CheckConstraint("selected_levels <@ ARRAY['a1','a2','b1','b2','c1','c2']::TEXT[]", name='bot_users_levels_check'),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_index('bot_users_active_idx', 'bot_users', ['is_active', 'onboarding_completed'], unique=False)
    op.create_table('oald_audio_files',
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('audio_data', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('filename', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('download_status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('downloaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("download_status IN ('pending', 'downloaded', 'failed')", name='oald_audio_status_check'),
    sa.CheckConstraint('attempt_count >= 0', name='oald_audio_attempt_count_check'),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name='oald_audio_size_check'),
    sa.PrimaryKeyConstraint('source_url')
    )
    op.create_index('oald_audio_sha256_idx', 'oald_audio_files', ['sha256'], unique=False, postgresql_where=sa.text("sha256 != ''"))
    op.create_table('oald_entries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('word_us', sa.Text(), nullable=False),
    sa.Column('word_gb', sa.Text(), nullable=False),
    sa.Column('lexical_category', sa.Text(), nullable=False),
    sa.Column('cefr', sa.String(length=2), nullable=False),
    sa.Column('definition_url_oxford', sa.Text(), nullable=False),
    sa.Column('definition_url_cambridge', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('ipa_us', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('ipa_gb', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('audio_source_us', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('audio_source_gb', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("btrim(definition_url_oxford) <> ''", name='oald_entries_definition_url_check'),
    sa.CheckConstraint("btrim(lexical_category) <> ''", name='oald_entries_category_check'),
    sa.CheckConstraint("btrim(word_gb) <> ''", name='oald_entries_word_gb_check'),
    sa.CheckConstraint("btrim(word_us) <> ''", name='oald_entries_word_us_check'),
    sa.CheckConstraint("cefr IN ('a1', 'a2', 'b1', 'b2', 'c1', 'c2')", name='oald_entries_cefr_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_url_oxford')
    )
    op.create_index('oald_entries_active_idx', 'oald_entries', ['is_active', 'cefr'], unique=False)
    op.create_index('oald_entries_category_idx', 'oald_entries', ['lexical_category'], unique=False)
    op.create_index('oald_entries_cefr_idx', 'oald_entries', ['cefr'], unique=False)
    op.create_index('oald_entries_translations_idx', 'oald_entries', ['translations'], unique=False, postgresql_using='gin')
    op.create_index('oald_entries_word_gb_idx', 'oald_entries', ['word_gb'], unique=False)
    op.create_index('oald_entries_word_us_category_idx', 'oald_entries', ['word_us', 'lexical_category'], unique=False)
    op.create_index('oald_entries_word_us_idx', 'oald_entries', ['word_us'], unique=False)
    op.create_table('bot_telegram_audio_cache',
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('send_method', sa.Text(), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("send_method IN ('voice', 'audio', 'document')", name='bot_audio_cache_method_check'),
    sa.ForeignKeyConstraint(['source_url'], ['oald_audio_files.source_url'], ),
    sa.PrimaryKeyConstraint('source_url', 'send_method')
    )
    op.create_table('bot_user_cards',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_id', sa.BigInteger(), nullable=False),
    sa.Column('dialect', sa.String(length=4), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_url_gb', sa.Text(), nullable=True),
    sa.Column('scheduled_slot', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'reserved'"), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('error_type', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('error_message', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("dialect IN ('us', 'gb', 'both')", name='bot_user_cards_dialect_check'),
    sa.CheckConstraint("status IN ('reserved', 'delivered', 'failed')", name='bot_user_cards_status_check'),
    sa.ForeignKeyConstraint(['entry_id'], ['oald_entries.id'], ),
    sa.ForeignKeyConstraint(['source_url'], ['oald_audio_files.source_url'], ),
    sa.ForeignKeyConstraint(['source_url_gb'], ['oald_audio_files.source_url'], ),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['bot_users.telegram_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id', 'entry_id', name='bot_user_cards_telegram_user_id_entry_id_key'),
    sa.UniqueConstraint('telegram_user_id', 'scheduled_slot', name='bot_user_cards_telegram_user_id_scheduled_slot_key')
    )
    op.create_index('bot_user_cards_delivered_at_idx', 'bot_user_cards', ['delivered_at'], unique=False)
    op.create_index('bot_user_cards_entry_idx', 'bot_user_cards', ['entry_id'], unique=False)
    op.create_index('bot_user_cards_error_idx', 'bot_user_cards', ['status', 'error_type', 'created_at'], unique=False)
    op.create_index('bot_user_cards_user_status_idx', 'bot_user_cards', ['telegram_user_id', 'status'], unique=False)
    op.create_table('oald_audio_variants',
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('variant_type', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('audio_data', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('filename', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('conversion_status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('last_error', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("conversion_status IN ('pending', 'prepared', 'failed')", name='oald_audio_variant_status_check'),
    sa.CheckConstraint("variant_type IN ('telegram_voice_opus')", name='oald_audio_variant_type_check'),
    sa.CheckConstraint('attempt_count >= 0', name='oald_audio_variant_attempt_count_check'),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name='oald_audio_variant_size_check'),
    sa.ForeignKeyConstraint(['source_url'], ['oald_audio_files.source_url'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_url', 'variant_type')
    )
    op.create_index('oald_audio_variants_status_idx', 'oald_audio_variants', ['variant_type', 'conversion_status'], unique=False)
    op.create_table('oald_entry_audio_sources',
    sa.Column('entry_id', sa.BigInteger(), nullable=False),
    sa.Column('dialect', sa.String(length=2), nullable=False),
    sa.Column('source_position', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.CheckConstraint("dialect IN ('us', 'gb')", name='oald_entry_audio_dialect_check'),
    sa.CheckConstraint('source_position >= 0', name='oald_entry_audio_position_check'),
    sa.ForeignKeyConstraint(['entry_id'], ['oald_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_url'], ['oald_audio_files.source_url'], ),
    sa.PrimaryKeyConstraint('entry_id', 'dialect', 'source_position')
    )
    op.create_index('oald_entry_audio_dialect_idx', 'oald_entry_audio_sources', ['dialect'], unique=False)
    op.create_index('oald_entry_audio_source_url_idx', 'oald_entry_audio_sources', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('oald_entry_audio_source_url_idx', table_name='oald_entry_audio_sources')
    op.drop_index('oald_entry_audio_dialect_idx', table_name='oald_entry_audio_sources')
    op.drop_table('oald_entry_audio_sources')
    op.drop_index('oald_audio_variants_status_idx', table_name='oald_audio_variants')
    op.drop_table('oald_audio_variants')
    op.drop_index('bot_user_cards_user_status_idx', table_name='bot_user_cards')
    op.drop_index('bot_user_cards_error_idx', table_name='bot_user_cards')
    op.drop_index('bot_user_cards_entry_idx', table_name='bot_user_cards')
    op.drop_index('bot_user_cards_delivered_at_idx', table_name='bot_user_cards')
    op.drop_table('bot_user_cards')
    op.drop_table('bot_telegram_audio_cache')
    op.drop_index('oald_entries_word_us_idx', table_name='oald_entries')
    op.drop_index('oald_entries_word_us_category_idx', table_name='oald_entries')
    op.drop_index('oald_entries_word_gb_idx', table_name='oald_entries')
    op.drop_index('oald_entries_translations_idx', table_name='oald_entries', postgresql_using='gin')
    op.drop_index('oald_entries_cefr_idx', table_name='oald_entries')
    op.drop_index('oald_entries_category_idx', table_name='oald_entries')
    op.drop_index('oald_entries_active_idx', table_name='oald_entries')
    op.drop_table('oald_entries')
    op.drop_index('oald_audio_sha256_idx', table_name='oald_audio_files', postgresql_where=sa.text("sha256 != ''"))
    op.drop_table('oald_audio_files')
    op.drop_index('bot_users_active_idx', table_name='bot_users')
    op.drop_table('bot_users')
    op.drop_table('bot_scheduler_runs')
    # ### end Alembic commands ###
